export const listing = [
  'Random Listings',
  'Price - High To Low',
  'Price - Low To High',
  'Gemstones - A to Z',
  'Gemstones - Z to A',
  'Size - Largest To Smallest',
  'Size - Smallest To Largest',
];
export const data = [
  {
    name: 'Sapphire',
    image: require('../../images/sapphire1.jpg'),
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: `Sapphire is known as a wisdom stone, with each color carrying its own special wisdom. Sapphire calms the mind and helps you to focus. It also deals with unwanted thoughts and is a good choice for anyone seeking to deal with over-thinking or over-analyzing. `,
  },
  {
    name: 'Amethyst',
    image: require('../../images/amethyst1.jpg'),
    shape: 'oval',
    size: '6.2mm x 5.2mm',
    price: '$104.15',
    text: 'Amethyst is one of the most famous crystals because of its beautiful coloration as well as its spiritual and literal meaning.The spiritual meaning of Amethyst is groundedness, tranquility, and calm. The meaning of Amethyst is “not intoxicated” – its name translates from the Greek word améthystos.',
  },
  {
    name: 'Amethyst',
    image: require('../../images/amethyst2.jpg'),
    shape: 'pear',
    size: '6.8mm x 3.2mm',
    price: '$104.15',
    text: 'Amethyst is one of the most famous crystals because of its beautiful coloration as well as its spiritual and literal meaning.The spiritual meaning of Amethyst is groundedness, tranquility, and calm. The meaning of Amethyst is “not intoxicated” – its name translates from the Greek word améthystos.',
  },

  {
    name: 'Diamond',
    image: require('../../images/diamond1.jpg'),
    shape: 'diamond',
    size: '5.0mm x 3.2mm',
    price: '$1060.15',
    text: 'Diamond is a solid form of the element carbon with its atoms arranged in a crystal structure called diamond cubic. Diamond has the highest hardness and thermal conductivity of any natural material, properties that are used in major industrial applications such as cutting and polishing tools. ',
  },
  {
    name: 'Diamond',
    image: require('../../images/diamond2.jpg'),
    shape: 'round',
    size: '5.5mm x 5.1mm',
    price: '$2060.15',
    text: 'Diamond is a solid form of the element carbon with its atoms arranged in a crystal structure called diamond cubic. Diamond has the highest hardness and thermal conductivity of any natural material, properties that are used in major industrial applications such as cutting and polishing tools. ',
  },

  {
    name: 'Citrine',
    image: require('../../images/citrine1.jpg'),
    shape: 'round',
    size: '6.5mm x 6.2mm',
    price: '$35.15',
    text: 'Its pale yellow color is what gives it its name, Citrine, coming from the French citron, meaning lemon. Citrine has a deep spiritual meaning, too. The spiritual meaning of Citrine is its yellow hues symbolizing the spiritual qualities of joy, abundance, and transmutation.',
  },
  {
    name: 'Citrine',
    image: require('../../images/citrine2.png'),
    shape: 'diamond',
    size: '7.5mm x 6.0mm',
    price: '$49.15',
    text: 'Its pale yellow color is what gives it its name, Citrine, coming from the French citron, meaning lemon. Citrine has a deep spiritual meaning, too. The spiritual meaning of Citrine is its yellow hues symbolizing the spiritual qualities of joy, abundance, and transmutation.',
  },
  {
    name: 'Citrine',
    image: require('../../images/citrine3.jpg'),
    shape: 'trillion',
    size: '6.2mm x 4.0mm',
    price: '$58.15',
    text: 'Its pale yellow color is what gives it its name, Citrine, coming from the French citron, meaning lemon. Citrine has a deep spiritual meaning, too. The spiritual meaning of Citrine is its yellow hues symbolizing the spiritual qualities of joy, abundance, and transmutation.',
  },

  {
    name: 'Aventurine',
    image: require('../../images/aventurine1.jpg'),
    shape: 'pear',
    size: '5.2mm x 4.8mm',
    price: '$79.15',
    text: 'The name `Aventurine` comes from the beautiful shimmering finish of this stone. Its name relates to the word aventurescence, which refers to the “glittery” effect of tiny particles of highly reflective mineral contained in a less reflective whole.',
  },
  {
    name: 'Emerald',
    image: require('../../images/emerald1.jpg'),
    shape: 'diamond',
    size: '6.2mm x 4.8mm',
    price: '$279.15',
    text: 'Emerald is a life-affirming stone and one of infinite patience. Emerald is the stone of love and friendship and keeps partnerships in balance. This gem also opens up to your latent abilities and promotes the gathering of wisdom from the mental planes. ',
  },
  {
    name: 'Emerald',
    image: require('../../images/emerald2.jpg'),
    shape: 'round',
    size: '6.8mm x 5.2mm',
    price: '$279.15',
    text: 'Emerald is a life-affirming stone and one of infinite patience. Emerald is the stone of love and friendship and keeps partnerships in balance. This gem also opens up to your latent abilities and promotes the gathering of wisdom from the mental planes. ',
  },
  {
    name: 'Ruby',
    image: require('../../images/ruby1.jpg'),
    shape: 'oval',
    size: '8mm x 6.6mm',
    price: '$679.15',
    text: 'Rubies are a form of the mineral corundum. The deep red color of a good quality Ruby is heartwarming and uplifting to look upon. You can feel the vigor of the energies of this remarkable stone as soon as you touch it or have it near you.',
  },
  {
    name: 'Ruby',
    image: require('../../images/ruby2.jpg'),
    shape: 'round',
    size: '8mm x 8mm',
    price: '$829.28',
    text: 'Rubies are a form of the mineral corundum. The deep red color of a good quality Ruby is heartwarming and uplifting to look upon. You can feel the vigor of the energies of this remarkable stone as soon as you touch it or have it near you.',
  },
  {
    name: 'Agate',
    image: require('../../images/agate1.jpg'),
    shape: 'pear',
    size: '7mm x 5mm',
    price: '$29.28',
    text: 'Rubies are a form of the mineral corundum. The deep red color of a good quality Ruby is heartwarming and uplifting to look upon. You can feel the vigor of the energies of this remarkable stone as soon as you touch it or have it near you.',
  },
  {
    name: 'Amazonite',
    image: require('../../images/amazonite1.jpg'),
    shape: 'oval',
    size: '6.8mm x 5.9mm',
    price: '$48.28',
    text: 'Rubies are a form of the mineral corundum. The deep red color of a good quality Ruby is heartwarming and uplifting to look upon. You can feel the vigor of the energies of this remarkable stone as soon as you touch it or have it near you.',
  },
  {
    name: 'Aquamarine',
    image: require('../../images/aquamarine1.jpg'),
    shape: 'pear',
    size: '6.8mm x 5.9mm',
    price: '$48.28',
    text: 'Rubies are a form of the mineral corundum. The deep red color of a good quality Ruby is heartwarming and uplifting to look upon. You can feel the vigor of the energies of this remarkable stone as soon as you touch it or have it near you.',
  },
  {
    name: 'Aquamarine',
    image: require('../../images/aquamarine2.jpg'),
    shape: 'pear',
    size: '6.8mm x 5.9mm',
    price: '$48.28',
    text: 'Aquamarine is the green-blue to blue variety of the mineral beryl. (Emerald is the green to bluish green variety of the same mineral. Its color is usually a light pastel greenish blue.',
  },
  {
    name: 'Opal',
    image: require('../../images/opal1.jpg'),
    shape: 'pear',
    size: '6.8mm x 5.9mm',
    price: '$48.28',
    text: 'Opal is the product of seasonal rains that drenched dry ground in regions such as Australia’s semi-desert “outback.” The showers soaked deep into ancient underground rock, carrying dissolved silica (a compound of silicon and oxygen downward.',
  },
  {
    name: 'Zircon',
    image: require('../../images/zircon1.jpg'),
    shape: 'round',
    size: '6.8mm x 5.9mm',
    price: '$48.28',
    text: 'Colorless zircon is well known for its brilliance and flashes of multicolored light, called fire. These two zircon properties are close enough to the properties of diamond to account for centuries of confusion between the two gems.',
  },
];
