export const listing = [
  'Random Listings',
  'Price - High To Low',
  'Price - Low To High',
  'Gemstones - A to Z',
  'Gemstones - Z to A',
  'Size - Largest To Smallest',
  'Size - Smallest To Largest',
];
export const data = [
  {
    name: 'agate1',
    image: '/images/agate1.jpg',
    shape: 'pear',
    size: '8.2 carat',
    price: '$22.75',
    text: 'Agate is formed in the cavities of igneous rocks, through deposits of silica which settle into the characteristic banded patterns we see in all forms of this semi-precious stone. It measures 7 on the Mohs scale of hardness.',
  },
  {
    name: 'agate2',
    image: '/images/agate2.jpg',
    shape: 'pear',
    size: '6.6 carat',
    price: '$19.55',
    text: '',
  },
  {
    name: 'agate3',
    image: '/images/agate3.jpg',
    shape: 'pear',
    size: '9.5 carat',
    price: '$47.50',
    text: '',
  },
  {
    name: 'agate4',
    image: '/images/agate4.jpg',
    shape: 'pear',
    size: '12.9 carat',
    price: '$64.75',
    text: '',
  },
  {
    name: 'agate5',
    image: '/images/agate5.jpg',
    shape: 'pear',
    size: '7.0 carat',
    price: '$20.99',
    text: '',
  },
  {
    name: 'agate6',
    image: '/images/agate6.jpg',
    shape: 'pear',
    size: '3.9 carat',
    price: '$12.99',
    text: '',
  },
  {
    name: 'agate7',
    image: '/images/agate7.jpg',
    shape: 'pear',
    size: '6.2 carat',
    price: '$52.15',
    text: '',
  },
  {
    name: 'amazonite1',
    image: '/images/amazonite1.jpg',
    shape: 'pear',
    size: '20.0 carat',
    price: '$62.50',
    text: '',
  },
  {
    name: 'amazonite2',
    image: '/images/amazonite2.jpg',
    shape: 'pear',
    size: '15.0 carat',
    price: '$55.50',
    text: '',
  },
  {
    name: 'amazonite3',
    image: '/images/amazonite3.jpg',
    shape: 'pear',
    size: '6.2 carat',
    price: '$42.15',
    text: '',
  },
  {
    name: 'amazonite4',
    image: '/images/amazonite4.jpg',
    shape: 'pear',
    size: '26.84 carat',
    price: '$82.99',
    text: 'Also called "Amazon stone, amazonite is the only microcline you are likely to encounter as a gemstone. Microclines are potassium feldspars with a triclinic crystal structure Amazonite color can range from pale green to dark green and blue-green. These specimens usually (but not always) show white mottling.',
  },
  {
    name: 'amazonite5',
    image: '/images/amazonite5.jpg',
    shape: 'pear',
    size: '42.24 carat',
    price: '$110.00',
    text: '',
  },
  {
    name: 'amazonite6',
    image: '/images/amazonite6.jpg',
    shape: 'pear',
    size: '64.20 carat',
    price: '$168.99',
    text: '',
  },
  {
    name: 'amazonite7',
    image: '/images/amazonite7.jpg',
    shape: 'pear',
    size: '894.26.84carat',
    price: '$42.15',
    text: ``,
  },
  {
    name: 'amethyst1',
    image: '/images/amethyst1.jpg',
    shape: 'pear',
    size: '894.26.84carat',
    price: '$42.15',
    text: '',
  },
  {
    name: 'amethyst2',
    image: '/images/amethyst2.jpg',
    shape: 'pear',
    size: '894.26.84carat',
    price: '$42.15',
    text: '',
  },
  {
    name: 'amethyst3',
    image: '/images/amethyst3.jpg',
    shape: 'pear',
    size: '894.26.84carat',
    price: '$42.15',
    text: '',
  },
  {
    name: 'amethyst4',
    image: '/images/amethyst4.jpg',
    shape: 'pear',
    size: '894.26.84carat',
    price: '$42.15',
    text: '',
  },
  {
    name: 'amethyst5',
    image: '/images/amethyst5.jpg',
    shape: 'pear',
    size: '894.26.84carat',
    price: '$42.15',
    text: '',
  },
  {
    name: 'amethyst6',
    image: '/images/amethyst6.jpg',
    shape: 'pear',
    size: '894.26.84carat',
    price: '$42.15',
    text: '',
  },
  {
    name: 'amethyst7',
    image: '/images/amethyst7.jpg',
    shape: 'pear',
    size: '894.26.84carat',
    price: '$42.15',
    text: ``,
  },
  {
    name: 'amethyst8',
    image: '/images/amethyst8.jpg',
    shape: 'oval',
    size: '6.2mm x 5.2mm',
    price: '$104.15',
    text: 'Amethyst is one of the most famous crystals because of its beautiful coloration as well as its spiritual and literal meaning.The spiritual meaning of Amethyst is groundedness, tranquility, and calm. The meaning of Amethyst is “not intoxicated” – its name translates from the Greek word améthystos.',
  },
  {
    name: 'aquamarine1',
    image: '/images/aquamarine1.jpg',
    shape: 'pear',
    size: '894.26.84carat',
    price: '$42.15',
    text: '',
  },
  {
    name: 'aquamarine2',
    image: '/images/aquamarine2.jpg',
    shape: 'pear',
    size: '894.26.84carat',
    price: '$42.15',
    text: '',
  },
  {
    name: 'aquamarine3',
    image: '/images/aquamarine3.jpg',
    shape: 'pear',
    size: '894.26.84carat',
    price: '$42.15',
    text: '',
  },
  {
    name: 'aquamarine4',
    image: '/images/aquamarine4.jpg',
    shape: 'pear',
    size: '894.26.84carat',
    price: '$42.15',
    text: '',
  },
  {
    name: 'aquamarine5',
    image: '/images/aquamarine5.jpg',
    shape: 'pear',
    size: '894.26.84carat',
    price: '$42.15',
    text: '',
  },
  {
    name: 'aquamarine6',
    image: '/images/aquamarine6.jpg',
    shape: 'pear',
    size: '894.26.84carat',
    price: '$42.15',
    text: '',
  },
  {
    name: 'aquamarine7',
    image: '/images/aquamarine7.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: 'Aquamarine is the green-blue to blue variety of the mineral beryl. (Emerald is the green to bluish green variety of the same mineral. Its color is usually a light pastel greenish blue.',
  },
  {
    name: 'citrine1',
    image: '/images/citrine1.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: '',
  },
  {
    name: 'citrine2',
    image: '/images/citrine2.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: '',
  },
  {
    name: 'citrine3',
    image: '/images/citrine3.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: '',
  },
  {
    name: 'citrine4',
    image: '/images/citrine4.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: '',
  },
  {
    name: 'citrine5',
    image: '/images/citrine5.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: 'Its pale yellow color is what gives it its name, Citrine, coming from the French citron, meaning lemon. Citrine has a deep spiritual meaning, too. The spiritual meaning of Citrine is its yellow hues symbolizing the spiritual qualities of joy, abundance, and transmutation',
  },
  {
    name: 'citrine6',
    image: '/images/citrine6.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: '',
  },
  {
    name: 'citrine7',
    image: '/images/citrine7.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: ``,
  },
  {
    name: 'diamond1',
    image: '/images/diamond1.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: '',
  },
  {
    name: 'diamond2',
    image: '/images/diamond2.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: '',
  },
  {
    name: 'diamond3',
    image: '/images/diamond3.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: '',
  },
  {
    name: 'diamond4',
    image: '/images/diamond4.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: '',
  },
  {
    name: 'diamond5',
    image: '/images/diamond5.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: 'Diamond is a solid form of the element carbon with its atoms arranged in a crystal structure called diamond cubic. Diamond has the highest hardness and thermal conductivity of any natural material, properties that are used in major industrial applications such as cutting and polishing tools. ',
  },
  {
    name: 'diamond6',
    image: '/images/diamond6.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: '',
  },
  {
    name: 'emerald1',
    image: '/images/emerald1.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: '',
  },
  {
    name: 'emerald2',
    image: '/images/emerald2.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: '',
  },
  {
    name: 'emerald3',
    image: '/images/emerald3.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: '',
  },
  {
    name: 'emerald4',
    image: '/images/emerald4.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: '',
  },
  {
    name: 'emerald5',
    image: '/images/emerald5.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: '',
  },
  {
    name: 'emerald6',
    image: '/images/emerald6.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: 'Emerald is a life-affirming stone and one of infinite patience. Emerald is the stone of love and friendship and keeps partnerships in balance. This gem also opens up to your latent abilities and promotes the gathering of wisdom from the mental planes.',
  },
  {
    name: 'emerald7',
    image: '/images/emerald7.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: ``,
  },
  {
    name: 'opal1',
    image: '/images/opal1.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: '',
  },
  {
    name: 'opal2',
    image: '/images/opal2.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: '',
  },
  {
    name: 'opal3',
    image: '/images/opal3.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: '',
  },
  {
    name: 'opal4',
    image: '/images/opal4.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: '',
  },
  {
    name: 'opal5',
    image: '/images/opal5.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: '',
  },
  {
    name: 'opal6',
    image: '/images/opal6.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: '',
  },
  {
    name: 'opal7',
    image: '/images/opal7.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: `Opal is the product of seasonal rains that drenched dry ground in regions such as Australia’s semi-desert “outback.” The showers soaked deep into ancient underground rock, carrying dissolved silica (a compound of silicon and oxygen downward.`,
  },
  {
    name: 'ruby1',
    image: '/images/ruby1.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: '',
  },
  {
    name: 'ruby2',
    image: '/images/ruby2.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: '',
  },
  {
    name: 'ruby3',
    image: '/images/ruby3.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: '',
  },
  {
    name: 'ruby4',
    image: '/images/ruby4.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: '',
  },
  {
    name: 'ruby5',
    image: '/images/ruby5.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: '',
  },
  {
    name: 'ruby6',
    image: '/images/ruby6.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: 'Rubies are a form of the mineral corundum. The deep red color of a good quality Ruby is heartwarming and uplifting to look upon. You can feel the vigor of the energies of this remarkable stone as soon as you touch it or have it near you.',
  },
  {
    name: 'ruby7',
    image: '/images/ruby7.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: ``,
  },
  {
    name: 'sapphire1',
    image: '/images/sapphire1.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: '',
  },
  {
    name: 'sapphire2',
    image: '/images/sapphire2.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: '',
  },
  {
    name: 'sapphire3',
    image: '/images/sapphire3.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: 'Sapphire is known as a wisdom stone, with each color carrying its own special wisdom. Sapphire calms the mind and helps you to focus. It also deals with unwanted thoughts and is a good choice for anyone seeking to deal with over-thinking or over-analyzing. ',
  },
  {
    name: 'sapphire4',
    image: '/images/sapphire4.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: '',
  },
  {
    name: 'sapphire5',
    image: '/images/sapphire5.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: '',
  },
  {
    name: 'sapphire6',
    image: '/images/sapphire6.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: '',
  },
  {
    name: 'sapphire7',
    image: '/images/sapphire7.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: ``,
  },

  {
    name: 'zircon1',
    image: '/images/zircon1.jpg',
    shape: 'round',
    size: '6.8mm x 5.9mm',
    price: '$48.28',
    text: '',
  },
  {
    name: 'zircon2',
    image: '/images/zircon2.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: 'Colorless zircon is well known for its brilliance and flashes of multicolored light, called fire. These two zircon properties are close enough to the properties of diamond to account for centuries of confusion between the two gems.',
  },
  {
    name: 'zircon3',
    image: '/images/zircon3.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: '',
  },
  {
    name: 'zircon4',
    image: '/images/zircon4.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: '',
  },
  {
    name: 'zircon5',
    image: '/images/zircon5.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: '',
  },
  {
    name: 'zircon6',
    image: '/images/zircon6.jpg',
    shape: 'pear',
    size: '6.2mm x 3.9mm',
    price: '$42.15',
    text: '',
  },
];
